# -----------------------------------------------------------
## Figma configuration
# -----------------------------------------------------------

# Adding your figma personal token to a .env file as FIGMATOKEN is highly recommended
# Values in the .env file take precedence over the figma token here
figmaconfig:
  token: xxxx-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  scale: 2
  format: png
  figmaurls: true
  home: true
  documents:
    - document: kY1yaGDw5nA6d5whK7NvjC

# -----------------------------------------------------------
## Jekyll configuration
# -----------------------------------------------------------

title: Figma Designdoc
description: >- # this means to ignore newlines until "baseurl:"
  A repository to show how you can build a website using figma and actions.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/

# Jekyll Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  sass_dir: _sass
  style: compressed
